export default {
  short: "en",
  navPaths: {
    back: "Back",
    home: "Home",
    products: "Products",
    inventory: "Inventory",
    settings: "Settings",
    providers: "Providers",
    locations: "Locations",
    categories: "Categories",
    origins: "Origins",
  },
  dashboard: {
    products: "Products",
    entries: "Inventory Entries",
    movements: "Inventory Movements",
  },
  general: {
    export: "Export",
    import: "Import",
    noImages: "No images",
    cancel: "Cancel",
    exit: "Exit",
    search: "Search...",
    save: "Save",
    add: "Add",
    searchInput: "Search...",
    images: "Images",
    noItems: "No items",
    delete: "Delete",
    edit: "Edit",
    error: "An error occurred",
    see: "See",
    sure: "Are you sure?",
    imSure: "I'm sure",
    pleaseConfirm: "Please confirm",
    deletedSuccess: "Successfully deleted",
    images: "Images",
  },
  origins: {
    selfName: "Origin",
    new: "New origin",
    edit: "Edit origin",
    general: {
      id: "ID",
      name: "Name",
    },
    create: {
      success: "The origin has been successfully created",
      validations: {
        badParams: "The name is not valid",
        editted: "The origin has been successfully edited",
      },
    },
  },
  providers: {
    selfName: "Provider",
    new: "New provider",
    edit: "Edit provider",
    general: {
      id: "ID",
      name: "Name",
      doc: "Document Number",
    },
    create: {
      success: "The provider has been successfully created",
      validations: {
        badParams: "The name or Document Number is not valid",
        editted: "The provider has been successfully edited",
      },
    },
  },
  inventory: {
    general: {
      seeEntry: "View Inventory Entry",
      id: "ID",
      name: "Name",
      quantity: "Quantity",
      user: "User",
      status: "Status",
      searchOutputEntry: "Search by ID or User...",
      newEntry: "New Inventory Entry",
      newOutput: "New Inventory Output",
      addProduct: "Add Product",
      date: "Date",
      seeImages: "View Images",
    },
    edit: {
      editted: "Successfully edited",
      badParams: "All fields are required",
    },
    placeholder: {
      quantityEntry: "Enter a quantity to enter",
      quantityOutput: "Enter an output quantity",
      provider: "Select a provider",
      product: "Select a product",
      details: "Write a detail about this entry",
      images: "Select the images",
      description: "Write a description",
    },
    labels: {
      product: "Product",
      code: "Code",
      quantity: "Quantity",
      details: "Detail",
      provider: "Provider",
      description: "Description",
    },
    entryCreate: {
      success: "The entry has been successfully created",
      error: "Error creating the entry",
    },
    outputCreate: {
      success: "The output has been successfully created",
      stock: "The requested quantity is not in stock",
      quantity: "The requested quantity must be greater than 0",
      error: "Error creating the output",
    },
    entry: "Inventory Entry",
    entries: "Inventory Entries",
    output: "Inventory Output",
    outputs: "Inventory Outputs",
    stock: {
      true: "Available",
      false: "Not available",
    },
  },
  categories: {
    selfName: "Category",
    new: "New category",
    edit: "Edit category",
    general: {
      id: "ID",
      name: "Name",
    },
    create: {
      success: "The category has been successfully created",
      validations: {
        badParams: "The name is not valid",
        editted: "The category has been successfully edited",
      },
    },
  },
  login: {
    title: "Log In",
    button: "Enter",
    badLogin: "The username or password is incorrect",
    error: "Login error",
    labels: {
      username: "Username",
      password: "Password",
    },
  },
  locations: {
    selfName: "Location",
    new: "New location",
    edit: "Edit location",
    general: {
      id: "ID",
      name: "Name",
    },
    create: {
      success: "The location has been successfully created",
      validations: {
        badParams: "The name is not valid",
        editted: "The location has been successfully edited",
      },
    },
  },
  products: {
    search: "Search product",
    new: "New product",
    headers: {
      name: "Name",
      description: "Description",
      code: "Code",
      barCode: "Barcode",
      originProduct: "Product Origin",
      location: "Location",
    },
    selfName: "Product",
    create: {
      labels: {
        title: "Title",
        description: "Description",
        code: "Code",
        barcode: "Barcode",
        origin: "Product Origin",
        location: "Location",
        images: "Images",
        categories: "Categories",
      },
      validations: {
        code: {
          true: "The code is valid",
          false: "The code already exists",
          notValid: "The code is not valid",
        },
        barcode: {
          true: "The barcode is valid",
          notValid: "The barcode is not valid",
          false: "The barcode already exists",
        },
        success: "The product has been successfully created",
        badParams: "All fields are required",
        error: "Error creating the product",
      },
      placeholders: {
        title: "Enter the product title",
        description: "Enter the product description",
        origin: "Select the product origin",
        location: "Select the product location",
        code: "Enter the product code",
        images: "Select the images",
        barcode: "Enter the product barcode",
      },
      general: "General Information",
    },
    edit: {
      labels: {
        title: "Title",
        description: "Description",
        code: "Code",
        barcode: "Barcode",
        origin: "Product Origin",
        location: "Location",
        images: "Images",
        categories: "Categories",
      },
      validations: {
        code: {
          true: "The code is valid",
          false: "The code already exists",
          notValid: "The code is not valid",
        },
        barcode: {
          true: "The barcode is valid",
          notValid: "The barcode is not valid",
          false: "The barcode already exists",
        },
        success: "The product has been successfully edited",
        error: "Error editing the product",
      },
      placeholders: {
        title: "Enter the product title",
        description: "Enter the product description",
        origin: "Select the product origin",
        location: "Select the product location",
        code: "Enter the product code",
        images: "Select the images",
        barcode: "Enter the product barcode (Optional)",
      },
      general: "General Information",
    },
    createProductHeader: "Create new product",
    editProductHeader: "Edit product",
  },
  settings: {
    images: "Images",
    users: "Users",
    language: "Language",
  },
  tables: {
    of: "of",
    results: "results",
    pages: "pages",
    prev: "Previous",
    next: "Next",
  },
};
