export default {
  navPaths: {
    home: "Inicio",
    products: "Productos",
    inventory: "Inventario",
    settings: "Opciones",
    supplier: "Proveedores",
    locations: "Ubicaciones",
    categories: "Categorias",
    origins: "Origenes",
  },
  dashboard: {
    products: "Productos",
    entries: "Entradas de Inventario",
    movements: "Movimientos de Inventario",
  },
  general: { 
    export: "Exportar",
    cancel: "Cancelar",
    save: "Guardar",
    add: "Añadir",
    searchInput: "Buscar...",
    images: "Imagenes",
    noItems: "No hay elementos",
    delete: "Eliminar",
    edit: "Editar",
    see: "Ver",
  },
  products: {
    new: "Nuevo producto",
    headers: {
      name: "Nombre",
      description: "Descripción",
      code: "Código",
      barCode: "Código de barras",
      originProduct: "Origen del producto",
      location: "Ubicación",
    },
    selfName: "Producto",
    create: {
      labels: {
        title: "Título",
        description: "Descripción",
        code: "Código",
        barcode: "Código de Barras",
        origin: "Producto de Origen",
        location: "Ubicación",
        images: "Imagenes",
        categories: "Categorias",
      },
      validations: {
        code: {
          true: "El código es válido",
          false: "El código ya existe",
          notValid: "El código no es válido",
        },
        barcode: {
          true: "El código de barras es válido",
          notValid: "El código de barras no es válido",
          false: "El código de barras ya existe",
        },
        success: "El producto se ha creado correctamente",
        badParams: "Todos los campos son obligatorios",
        error: "Error al crear el producto",
      },
      placeholders: {
        title: "Escriba el título del producto",
        description: "Escriba la descripción del producto",
        origin: "Seleccione el origen del producto",
        location: "Seleccione la ubicación del producto",
        code: "Escriba el Código del producto",
        images: "Seleccione las imagenes",
        barcode: "Escriba el código de barras del producto (Opcional)",
      },
      general: "Información General",
    },
    createProductHeader: "Crear nuevo producto",
  }
};