export default {
  short: "fr",
  navPaths: {
    back: "Retour",
    home: "Accueil",
    products: "Produits",
    inventory: "Inventaire",
    settings: "Paramètres",
    providers: "Fournisseurs",
    locations: "Emplacements",
    categories: "Catégories",
    origins: "Origines",
  },
  dashboard: {
    products: "Produits",
    entries: "Entrées d'Inventaire",
    movements: "Mouvements d'Inventaire",
  },
  general: {
    export: "Exporter",
    import: "Importer",
    noImages: "Pas d'images",
    cancel: "Annuler",
    exit: "Quitter",
    search: "Chercher...",
    save: "Sauvegarder",
    add: "Ajouter",
    searchInput: "Chercher...",
    images: "Images",
    noItems: "Pas d'éléments",
    delete: "Supprimer",
    edit: "Modifier",
    error: "Une erreur s'est produite",
    see: "Voir",
    sure: "Êtes-vous sûr?",
    imSure: "Je suis sûr",
    pleaseConfirm: "Veuillez confirmer",
    deletedSuccess: "Supprimé avec succès",
    images: "Images",
  },
  origins: {
    selfName: "Origine",
    new: "Nouvelle origine",
    edit: "Modifier l'origine",
    general: {
      id: "ID",
      name: "Nom",
    },
    create: {
      success: "L'origine a été créée avec succès",
      validations: {
        badParams: "Le nom n'est pas valide",
        editted: "L'origine a été modifiée avec succès",
      },
    },
  },
  providers: {
    selfName: "Fournisseur",
    new: "Nouveau fournisseur",
    edit: "Modifier le fournisseur",
    general: {
      id: "ID",
      name: "Nom",
      doc: "Numéro de Document",
    },
    create: {
      success: "Le fournisseur a été créé avec succès",
      validations: {
        badParams: "Le nom ou le Numéro de Document n'est pas valide",
        editted: "Le fournisseur a été modifié avec succès",
      },
    },
  },
  inventory: {
    general: {
      seeEntry: "Voir l'Entrée d'Inventaire",
      id: "ID",
      name: "Nom",
      quantity: "Quantité",
      user: "Utilisateur",
      status: "Statut",
      searchOutputEntry: "Chercher par ID ou Utilisateur...",
      newEntry: "Nouvelle Entrée d'Inventaire",
      newOutput: "Nouvelle Sortie d'Inventaire",
      addProduct: "Ajouter un Produit",
      date: "Date",
      seeImages: "Voir les Images",
    },
    edit: {
      editted: "Modifié avec succès",
      badParams: "Tous les champs sont obligatoires",
    },
    placeholder: {
      quantityEntry: "Entrez une quantité à entrer",
      quantityOutput: "Entrez une quantité de sortie",
      provider: "Sélectionnez un fournisseur",
      product: "Sélectionnez un produit",
      details: "Écrivez un détail sur cette entrée",
      images: "Sélectionnez les images",
      description: "Écrivez une description",
    },
    labels: {
      product: "Produit",
      code: "Code",
      quantity: "Quantité",
      details: "Détail",
      provider: "Fournisseur",
      description: "Description",
    },
    entryCreate: {
      success: "L'entrée a été créée avec succès",
      error: "Erreur lors de la création de l'entrée",
    },
    outputCreate: {
      success: "La sortie a été créée avec succès",
      stock: "La quantité demandée n'est pas en stock",
      quantity: "La quantité demandée doit être supérieure à 0",
      error: "Erreur lors de la création de la sortie",
    },
    entry: "Entrée d'Inventaire",
    entries: "Entrées d'Inventaire",
    output: "Sortie d'Inventaire",
    outputs: "Sorties d'Inventaire",
    stock: {
      true: "Disponible",
      false: "Non disponible",
    },
  },
  categories: {
    selfName: "Catégorie",
    new: "Nouvelle catégorie",
    edit: "Modifier la catégorie",
    general: {
      id: "ID",
      name: "Nom",
    },
    create: {
      success: "La catégorie a été créée avec succès",
      validations: {
        badParams: "Le nom n'est pas valide",
        editted: "La catégorie a été modifiée avec succès",
      },
    },
  },
  login: {
    title: "Connexion",
    button: "Entrer",
    badLogin: "Le nom d'utilisateur ou le mot de passe est incorrect",
    error: "Erreur de connexion",
    labels: {
      username: "Nom d'utilisateur",
      password: "Mot de passe",
    },
  },
  locations: {
    selfName: "Emplacement",
    new: "Nouvel emplacement",
    edit: "Modifier l'emplacement",
    general: {
      id: "ID",
      name: "Nom",
    },
    create: {
      success: "L'emplacement a été créé avec succès",
      validations: {
        badParams: "Le nom n'est pas valide",
        editted: "L'emplacement a été modifié avec succès",
      },
    },
  },
  products: {
    search: "Chercher un produit",
    new: "Nouveau produit",
    headers: {
      name: "Nom",
      description: "Description",
      code: "Code",
      barCode: "Code-barres",
      originProduct: "Origine du produit",
      location: "Emplacement",
    },
    selfName: "Produit",
    create: {
      labels: {
        title: "Titre",
        description: "Description",
        code: "Code",
        barcode: "Code-barres",
        origin: "Produit d'Origine",
        location: "Emplacement",
        images: "Images",
        categories: "Catégories",
      },
      validations: {
        code: {
          true: "Le code est valide",
          false: "Le code existe déjà",
          notValid: "Le code n'est pas valide",
        },
        barcode: {
          true: "Le code-barres est valide",
          notValid: "Le code-barres n'est pas valide",
          false: "Le code-barres existe déjà",
        },
        success: "Le produit a été créé avec succès",
        badParams: "Tous les champs sont obligatoires",
        error: "Erreur lors de la création du produit",
      },
      placeholders: {
        title: "Entrez le titre du produit",
        description: "Entrez la description du produit",
        origin: "Sélectionnez l'origine du produit",
        location: "Sélectionnez l'emplacement du produit",
        code: "Entrez le code du produit",
        images: "Sélectionnez les images",
        barcode: "Entrez le code-barres du produit",
      },
      general: "Informations Générales",
    },
    edit: {
      labels: {
        title: "Titre",
        description: "Description",
        code: "Code",
        barcode: "Code-barres",
        origin: "Produit d'Origine",
        location: "Emplacement",
        images: "Images",
        categories: "Catégories",
      },
      validations: {
        code: {
          true: "Le code est valide",
          false: "Le code existe déjà",
          notValid: "Le code n'est pas valide",
        },
        barcode: {
          true: "Le code-barres est valide",
          notValid: "Le code-barres n'est pas valide",
          false: "Le code-barres existe déjà",
        },
        success: "Le produit a été modifié avec succès",
        error: "Erreur lors de la modification du produit",
      },
      placeholders: {
        title: "Entrez le titre du produit",
        description: "Entrez la description du produit",
        origin: "Sélectionnez l'origine du produit",
        location: "Sélectionnez l'emplacement du produit",
        code: "Entrez le code du produit",
        images: "Sélectionnez les images",
        barcode: "Entrez le code-barres du produit (Optionnel)",
      },
      general: "Informations Générales",
    },
    createProductHeader: "Créer un nouveau produit",
    editProductHeader: "Modifier le produit",
  },
  settings: {
    images: "Images",
    users: "Utilisateurs",
    language: "Langue",
  },
  images: {
    new: "Ajouter une image",
    addedSuccess: "Image ajoutée avec succès",
    sureDelete: "Elle sera supprimée de tous les produits, sorties et entrées",
  },
  users: {
    selfName: "Utilisateur",
    new: "Nouvel utilisateur",
    edit: "Modifier l'utilisateur",
    general: {
      id: "ID",
      fullname: "Nom Complet",
      username: "Nom d'utilisateur",
      password: "Mot de passe",
    },
    placeholders: {
      fullname: "Nom Complet",
      username: "Nom d'utilisateur",
      password: "Mot de passe, Laissez vide pour conserver",
      permissions: "Permissions",
    },
    permissions: {
      edit: "Modifier les permissions",
      editted: "Les permissions ont été modifiées avec succès",
    },
    create: {
      success: "L'utilisateur a été créé avec succès",
      validations: {
        badParams: "Le nom ou le nom d'utilisateur n'est pas valide",
        editted: "L'utilisateur a été modifié avec succès",
      },
    },
  },
  tables: {
    of: "de",
    results: "résultats",
    pages: "pages",
    prev: "Précédent",
    next: "Suivant",
  },
};
